### ISSUE TITLE
CSS 小技巧 (｡･∀･)ﾉﾞ

### ISSUE THREAD

**Issue by LinkXSystem** [LinkXSystem/learn-guide#8]
选择前端，便是选择 CSS

**Comment by LinkXSystem** [comment]
> backdrop 伪元素是啥

backdrop 伪元素主要用于设置元素全屏背景情况下，背景样式。

示例代码如下:

```css
video::backdrop {
  background: #f5f5f5;
}
```
